# Generated by Django 2.2.10 on 2020-07-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookworldapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='address',
        ),
    ]
